// Copyright (c) 2026 vikiea <vikiea@users.noreply.github.com>
// This code is released under the MIT License.
// See LICENSE for details.

// Package ageengine provides a Go wrapper around the filippo.io/age encryption library.
// It is designed to be compiled with gomobile for use on Android.
package ageengine

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"os"
	"strings"

	"filippo.io/age"
	"filippo.io/age/armor"
)

// KeyPairResult holds the public and private key strings generated by GenerateKeyPair.
type KeyPairResult struct {
	PublicKey  string
	PrivateKey string
}

// GenerateKeyPair generates a new X25519 key pair.
// Returns a KeyPairResult struct so that gomobile generates a matching Java/Kotlin class.
func GenerateKeyPair() (*KeyPairResult, error) {
	identity, err := age.GenerateX25519Identity()
	if err != nil {
		return nil, fmt.Errorf("failed to generate key pair: %w", err)
	}
	return &KeyPairResult{
		PublicKey:  identity.Recipient().String(),
		PrivateKey: identity.String(),
	}, nil
}

// EncryptWithPassphrase encrypts data using a scrypt passphrase (binary output).
func EncryptWithPassphrase(data []byte, passphrase string) ([]byte, error) {
	recipient, err := age.NewScryptRecipient(passphrase)
	if err != nil {
		return nil, fmt.Errorf("failed to create scrypt recipient: %w", err)
	}

	var buf bytes.Buffer
	w, err := age.Encrypt(&buf, recipient)
	if err != nil {
		return nil, fmt.Errorf("failed to create encrypt writer: %w", err)
	}
	if _, err := w.Write(data); err != nil {
		return nil, fmt.Errorf("failed to write data: %w", err)
	}
	if err := w.Close(); err != nil {
		return nil, fmt.Errorf("failed to close encrypt writer: %w", err)
	}
	return buf.Bytes(), nil
}

// EncryptWithPublicKey encrypts data using an X25519 public key (binary output).
func EncryptWithPublicKey(data []byte, publicKey string) ([]byte, error) {
	recipient, err := age.ParseX25519Recipient(publicKey)
	if err != nil {
		return nil, fmt.Errorf("failed to parse public key: %w", err)
	}

	var buf bytes.Buffer
	w, err := age.Encrypt(&buf, recipient)
	if err != nil {
		return nil, fmt.Errorf("failed to create encrypt writer: %w", err)
	}
	if _, err := w.Write(data); err != nil {
		return nil, fmt.Errorf("failed to write data: %w", err)
	}
	if err := w.Close(); err != nil {
		return nil, fmt.Errorf("failed to close encrypt writer: %w", err)
	}
	return buf.Bytes(), nil
}

// DecryptWithPassphrase decrypts data using a scrypt passphrase.
// Auto-detects armored vs binary input.
func DecryptWithPassphrase(data []byte, passphrase string) ([]byte, error) {
	identity, err := age.NewScryptIdentity(passphrase)
	if err != nil {
		return nil, fmt.Errorf("failed to create scrypt identity: %w", err)
	}

	return decrypt(data, identity)
}

// DecryptWithPrivateKey decrypts data using an X25519 private key.
// Auto-detects armored vs binary input.
func DecryptWithPrivateKey(data []byte, privateKey string) ([]byte, error) {
	identity, err := age.ParseX25519Identity(privateKey)
	if err != nil {
		return nil, fmt.Errorf("failed to parse private key: %w", err)
	}

	return decrypt(data, identity)
}

// decrypt handles auto-detection of armored vs binary input and decrypts using the provided identity.
func decrypt(data []byte, identity age.Identity) ([]byte, error) {
	src := bytes.NewReader(data)

	// Try to detect armor by checking for the armor header
	var r io.Reader = src
	if bytes.HasPrefix(data, []byte("-----BEGIN AGE ENCRYPTED FILE-----")) {
		ar := armor.NewReader(src)
		r = ar
	}

	out, err := age.Decrypt(r, identity)
	if err != nil {
		return nil, fmt.Errorf("failed to decrypt: %w", err)
	}

	result, err := io.ReadAll(out)
	if err != nil {
		return nil, fmt.Errorf("failed to read decrypted data: %w", err)
	}
	return result, nil
}

// ReadFile reads the contents of a file at the given path.
func ReadFile(path string) ([]byte, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read file %s: %w", path, err)
	}
	return data, nil
}

// WriteFile writes data to a file at the given path.
func WriteFile(path string, data []byte) error {
	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", path, err)
	}
	return nil
}

// EncryptStreamToFile streams encryption from inputPath to outputPath using a passphrase.
// Memory usage is minimal (only pipe buffers, not the entire file).
func EncryptStreamToFile(inputPath, outputPath, passphrase string) error {
	recipient, err := age.NewScryptRecipient(passphrase)
	if err != nil {
		return fmt.Errorf("failed to create scrypt recipient: %w", err)
	}

	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer outFile.Close()

	w, err := age.Encrypt(outFile, recipient)
	if err != nil {
		return fmt.Errorf("failed to create encrypt writer: %w", err)
	}

	inFile, err := os.Open(inputPath)
	if err != nil {
		return fmt.Errorf("failed to open input file: %w", err)
	}
	defer inFile.Close()

	if _, err := io.Copy(w, inFile); err != nil {
		return fmt.Errorf("failed to encrypt data: %w", err)
	}
	if err := w.Close(); err != nil {
		return fmt.Errorf("failed to close encrypt writer: %w", err)
	}
	return nil
}

// EncryptStreamToFileWithKey streams encryption from inputPath to outputPath using a public key.
func EncryptStreamToFileWithKey(inputPath, outputPath, publicKey string) error {
	recipient, err := age.ParseX25519Recipient(publicKey)
	if err != nil {
		return fmt.Errorf("failed to parse public key: %w", err)
	}

	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer outFile.Close()

	w, err := age.Encrypt(outFile, recipient)
	if err != nil {
		return fmt.Errorf("failed to create encrypt writer: %w", err)
	}

	inFile, err := os.Open(inputPath)
	if err != nil {
		return fmt.Errorf("failed to open input file: %w", err)
	}
	defer inFile.Close()

	if _, err := io.Copy(w, inFile); err != nil {
		return fmt.Errorf("failed to encrypt data: %w", err)
	}
	if err := w.Close(); err != nil {
		return fmt.Errorf("failed to close encrypt writer: %w", err)
	}
	return nil
}

// DecryptStreamToFile streams decryption from inputPath to outputPath using a passphrase.
func DecryptStreamToFile(inputPath, outputPath, passphrase string) error {
	identity, err := age.NewScryptIdentity(passphrase)
	if err != nil {
		return fmt.Errorf("failed to create scrypt identity: %w", err)
	}
	return decryptStream(inputPath, outputPath, identity)
}

// DecryptStreamToFileWithKey streams decryption from inputPath to outputPath using a private key.
func DecryptStreamToFileWithKey(inputPath, outputPath, privateKey string) error {
	identity, err := age.ParseX25519Identity(privateKey)
	if err != nil {
		return fmt.Errorf("failed to parse private key: %w", err)
	}
	return decryptStream(inputPath, outputPath, identity)
}

func decryptStream(inputPath, outputPath string, identity age.Identity) error {
	inFile, err := os.Open(inputPath)
	if err != nil {
		return fmt.Errorf("failed to open input file: %w", err)
	}
	defer inFile.Close()

	// Peek first bytes to detect armor
	header := make([]byte, 35)
	n, _ := io.ReadFull(inFile, header)
	inFile.Seek(0, io.SeekStart)

	var r io.Reader = inFile
	if n >= 35 && bytes.HasPrefix(header[:n], []byte("-----BEGIN AGE ENCRYPTED FILE-----")) {
		ar := armor.NewReader(inFile)
		r = ar
	}

	out, err := age.Decrypt(r, identity)
	if err != nil {
		return fmt.Errorf("failed to decrypt: %w", err)
	}

	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer outFile.Close()

	if _, err := io.Copy(outFile, out); err != nil {
		return fmt.Errorf("failed to write decrypted data: %w", err)
	}
	return nil
}

// TarFiles creates a tar archive from the given file paths.
// fileNames[i] is the name to use in the archive for filePaths[i].
// Streams with minimal memory usage.
func TarFiles(filePaths []string, fileNames []string, outputPath string) error {
	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer outFile.Close()

	tw := tar.NewWriter(outFile)
	defer tw.Close()

	for i, path := range filePaths {
		info, err := os.Stat(path)
		if err != nil {
			return fmt.Errorf("failed to stat %s: %w", path, err)
		}

		header, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return fmt.Errorf("failed to create tar header: %w", err)
		}
		header.Name = fileNames[i]

		if err := tw.WriteHeader(header); err != nil {
			return fmt.Errorf("failed to write tar header: %w", err)
		}

		f, err := os.Open(path)
		if err != nil {
			return fmt.Errorf("failed to open %s: %w", path, err)
		}
		if _, err := io.Copy(tw, f); err != nil {
			f.Close()
			return fmt.Errorf("failed to write tar data: %w", err)
		}
		f.Close()
	}
	return nil
}

// TarGzipFiles creates a tar.gz archive from the given file paths.
// Streams with minimal memory usage (gzip internal buffer ~32KB).
func TarGzipFiles(filePaths []string, fileNames []string, outputPath string) error {
	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer outFile.Close()

	gw := gzip.NewWriter(outFile)
	defer gw.Close()

	tw := tar.NewWriter(gw)
	defer tw.Close()

	for i, path := range filePaths {
		info, err := os.Stat(path)
		if err != nil {
			return fmt.Errorf("failed to stat %s: %w", path, err)
		}

		header, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return fmt.Errorf("failed to create tar header: %w", err)
		}
		header.Name = fileNames[i]

		if err := tw.WriteHeader(header); err != nil {
			return fmt.Errorf("failed to write tar header: %w", err)
		}

		f, err := os.Open(path)
		if err != nil {
			return fmt.Errorf("failed to open %s: %w", path, err)
		}
		if _, err := io.Copy(tw, f); err != nil {
			f.Close()
			return fmt.Errorf("failed to write tar data: %w", err)
		}
		f.Close()
	}
	return nil
}

// TarSingleFile creates a tar archive containing a single file.
func TarSingleFile(filePath string, entryName string, outputPath string) error {
	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer outFile.Close()

	tw := tar.NewWriter(outFile)
	defer tw.Close()

	info, err := os.Stat(filePath)
	if err != nil {
		return fmt.Errorf("failed to stat %s: %w", filePath, err)
	}

	header, err := tar.FileInfoHeader(info, "")
	if err != nil {
		return fmt.Errorf("failed to create tar header: %w", err)
	}
	header.Name = entryName

	if err := tw.WriteHeader(header); err != nil {
		return fmt.Errorf("failed to write tar header: %w", err)
	}

	f, err := os.Open(filePath)
	if err != nil {
		return fmt.Errorf("failed to open %s: %w", filePath, err)
	}
	defer f.Close()

	if _, err := io.Copy(tw, f); err != nil {
		return fmt.Errorf("failed to write tar data: %w", err)
	}
	return nil
}

// TarFilesDelim creates a tar archive from newline-delimited file paths and names.
// gomobile cannot export []string, so we use "\n" as delimiter.
func TarFilesDelim(filePathsDelim string, fileNamesDelim string, outputPath string) error {
	paths := strings.Split(filePathsDelim, "\n")
	names := strings.Split(fileNamesDelim, "\n")
	return TarFiles(paths, names, outputPath)
}

// TarGzipFilesDelim creates a tar.gz archive from newline-delimited file paths and names.
// gomobile cannot export []string, so we use "\n" as delimiter.
func TarGzipFilesDelim(filePathsDelim string, fileNamesDelim string, outputPath string) error {
	paths := strings.Split(filePathsDelim, "\n")
	names := strings.Split(fileNamesDelim, "\n")
	return TarGzipFiles(paths, names, outputPath)
}
