// Copyright (c) 2026 vikiea <vikiea@users.noreply.github.com>
// This code is released under the MIT License.
// See LICENSE for details.

// Package ageengine provides a Go wrapper around the filippo.io/age encryption library.
// It is designed to be compiled with gomobile for use on Android.
package ageengine

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
	"sync/atomic"

	"filippo.io/age"
	"filippo.io/age/armor"
)

var errCancelled = errors.New("operation cancelled")

// CancelToken is shared by all stages of one operation. gomobile exposes it as
// a Java object, so Kotlin can stop Go streaming work without killing the app.
type CancelToken struct {
	cancelled atomic.Bool
}

func NewCancelToken() *CancelToken { return &CancelToken{} }

func (t *CancelToken) Cancel() {
	if t != nil {
		t.cancelled.Store(true)
	}
}

func (t *CancelToken) IsCancelled() bool {
	return t != nil && t.cancelled.Load()
}

type cancelReader struct {
	reader io.Reader
	token  *CancelToken
}

func (r cancelReader) Read(p []byte) (int, error) {
	if r.token.IsCancelled() {
		return 0, errCancelled
	}
	n, err := r.reader.Read(p)
	if r.token.IsCancelled() {
		return n, errCancelled
	}
	return n, err
}

// KeyPairResult holds the public and private key strings generated by GenerateKeyPair.
type KeyPairResult struct {
	PublicKey  string
	PrivateKey string
}

// GenerateKeyPair generates a post-quantum hybrid key by default. Pass
// "x25519" only when classic compatibility is explicitly required.
func GenerateKeyPair(keyType string) (*KeyPairResult, error) {
	switch strings.TrimSpace(strings.ToLower(keyType)) {
	case "", "post-quantum", "post_quantum", "hybrid":
		identity, err := age.GenerateHybridIdentity()
		if err != nil {
			return nil, fmt.Errorf("failed to generate post-quantum key pair: %w", err)
		}
		return &KeyPairResult{PublicKey: identity.Recipient().String(), PrivateKey: identity.String()}, nil
	case "x25519":
		identity, err := age.GenerateX25519Identity()
		if err != nil {
			return nil, fmt.Errorf("failed to generate X25519 key pair: %w", err)
		}
		return &KeyPairResult{PublicKey: identity.Recipient().String(), PrivateKey: identity.String()}, nil
	default:
		return nil, fmt.Errorf("unsupported key type %q", keyType)
	}
}

func parseRecipient(recipientText string) (age.Recipient, error) {
	recipients, err := age.ParseRecipients(strings.NewReader(strings.TrimSpace(recipientText) + "\n"))
	if err != nil || len(recipients) != 1 {
		if err == nil {
			err = fmt.Errorf("expected one recipient, got %d", len(recipients))
		}
		return nil, fmt.Errorf("failed to parse recipient: %w", err)
	}
	return recipients[0], nil
}

func parseIdentity(identityText string) (age.Identity, error) {
	identities, err := age.ParseIdentities(strings.NewReader(strings.TrimSpace(identityText) + "\n"))
	if err != nil || len(identities) != 1 {
		if err == nil {
			err = fmt.Errorf("expected one identity, got %d", len(identities))
		}
		return nil, fmt.Errorf("failed to parse identity: %w", err)
	}
	return identities[0], nil
}

// RecipientForIdentity validates an identity and returns its public recipient.
func RecipientForIdentity(identityText string) (string, error) {
	identity, err := parseIdentity(identityText)
	if err != nil {
		return "", err
	}
	switch typed := identity.(type) {
	case *age.HybridIdentity:
		return typed.Recipient().String(), nil
	case *age.X25519Identity:
		return typed.Recipient().String(), nil
	default:
		return "", fmt.Errorf("identity does not expose a recipient")
	}
}

// EncryptWithPassphrase encrypts data using a scrypt passphrase (binary output).
func EncryptWithPassphrase(data []byte, passphrase string) ([]byte, error) {
	recipient, err := age.NewScryptRecipient(passphrase)
	if err != nil {
		return nil, fmt.Errorf("failed to create scrypt recipient: %w", err)
	}

	var buf bytes.Buffer
	w, err := age.Encrypt(&buf, recipient)
	if err != nil {
		return nil, fmt.Errorf("failed to create encrypt writer: %w", err)
	}
	if _, err := w.Write(data); err != nil {
		return nil, fmt.Errorf("failed to write data: %w", err)
	}
	if err := w.Close(); err != nil {
		return nil, fmt.Errorf("failed to close encrypt writer: %w", err)
	}
	return buf.Bytes(), nil
}

// EncryptWithRecipient encrypts data using any native age recipient.
func EncryptWithRecipient(data []byte, recipientText string) ([]byte, error) {
	recipient, err := parseRecipient(recipientText)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	w, err := age.Encrypt(&buf, recipient)
	if err != nil {
		return nil, fmt.Errorf("failed to create encrypt writer: %w", err)
	}
	if _, err := w.Write(data); err != nil {
		return nil, fmt.Errorf("failed to write data: %w", err)
	}
	if err := w.Close(); err != nil {
		return nil, fmt.Errorf("failed to close encrypt writer: %w", err)
	}
	return buf.Bytes(), nil
}

// DecryptWithPassphrase decrypts data using a scrypt passphrase.
// Auto-detects armored vs binary input.
func DecryptWithPassphrase(data []byte, passphrase string) ([]byte, error) {
	identity, err := age.NewScryptIdentity(passphrase)
	if err != nil {
		return nil, fmt.Errorf("failed to create scrypt identity: %w", err)
	}

	return decrypt(data, identity)
}

// DecryptWithIdentity decrypts data using any native age identity.
// Auto-detects armored vs binary input.
func DecryptWithIdentity(data []byte, identityText string) ([]byte, error) {
	identity, err := parseIdentity(identityText)
	if err != nil {
		return nil, err
	}

	return decrypt(data, identity)
}

// decrypt handles auto-detection of armored vs binary input and decrypts using the provided identity.
func decrypt(data []byte, identity age.Identity) ([]byte, error) {
	src := bytes.NewReader(data)

	// Try to detect armor by checking for the armor header
	var r io.Reader = src
	if bytes.HasPrefix(data, []byte("-----BEGIN AGE ENCRYPTED FILE-----")) {
		ar := armor.NewReader(src)
		r = ar
	}

	out, err := age.Decrypt(r, identity)
	if err != nil {
		return nil, fmt.Errorf("failed to decrypt: %w", err)
	}

	result, err := io.ReadAll(out)
	if err != nil {
		return nil, fmt.Errorf("failed to read decrypted data: %w", err)
	}
	return result, nil
}

// ReadFile reads the contents of a file at the given path.
func ReadFile(path string) ([]byte, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read file %s: %w", path, err)
	}
	return data, nil
}

// WriteFile writes data to a file at the given path.
func WriteFile(path string, data []byte) error {
	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", path, err)
	}
	return nil
}

// EncryptStreamToFile streams encryption from inputPath to outputPath using a passphrase.
// Memory usage is minimal (only pipe buffers, not the entire file).
func EncryptStreamToFile(inputPath, outputPath, passphrase string, token *CancelToken) (err error) {
	recipient, err := age.NewScryptRecipient(passphrase)
	if err != nil {
		return fmt.Errorf("failed to create scrypt recipient: %w", err)
	}

	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer cleanupIncompleteOutput(outFile, outputPath, &err)

	w, err := age.Encrypt(outFile, recipient)
	if err != nil {
		return fmt.Errorf("failed to create encrypt writer: %w", err)
	}

	inFile, err := os.Open(inputPath)
	if err != nil {
		return fmt.Errorf("failed to open input file: %w", err)
	}
	defer inFile.Close()

	if _, err := io.Copy(w, cancelReader{reader: inFile, token: token}); err != nil {
		return fmt.Errorf("failed to encrypt data: %w", err)
	}
	if err := w.Close(); err != nil {
		return fmt.Errorf("failed to close encrypt writer: %w", err)
	}
	return nil
}

// EncryptStreamToFileWithRecipient streams encryption using any native age recipient.
func EncryptStreamToFileWithRecipient(inputPath, outputPath, recipientText string, token *CancelToken) (err error) {
	recipient, err := parseRecipient(recipientText)
	if err != nil {
		return err
	}

	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer cleanupIncompleteOutput(outFile, outputPath, &err)

	w, err := age.Encrypt(outFile, recipient)
	if err != nil {
		return fmt.Errorf("failed to create encrypt writer: %w", err)
	}

	inFile, err := os.Open(inputPath)
	if err != nil {
		return fmt.Errorf("failed to open input file: %w", err)
	}
	defer inFile.Close()

	if _, err := io.Copy(w, cancelReader{reader: inFile, token: token}); err != nil {
		return fmt.Errorf("failed to encrypt data: %w", err)
	}
	if err := w.Close(); err != nil {
		return fmt.Errorf("failed to close encrypt writer: %w", err)
	}
	return nil
}

// DecryptStreamToFile streams decryption from inputPath to outputPath using a passphrase.
func DecryptStreamToFile(inputPath, outputPath, passphrase string, token *CancelToken) error {
	identity, err := age.NewScryptIdentity(passphrase)
	if err != nil {
		return fmt.Errorf("failed to create scrypt identity: %w", err)
	}
	return decryptStream(inputPath, outputPath, identity, token)
}

// DecryptStreamToFileWithIdentity streams decryption using any native age identity.
func DecryptStreamToFileWithIdentity(inputPath, outputPath, identityText string, token *CancelToken) error {
	identity, err := parseIdentity(identityText)
	if err != nil {
		return err
	}
	return decryptStream(inputPath, outputPath, identity, token)
}

func decryptStream(inputPath, outputPath string, identity age.Identity, token *CancelToken) (err error) {
	inFile, err := os.Open(inputPath)
	if err != nil {
		return fmt.Errorf("failed to open input file: %w", err)
	}
	defer inFile.Close()

	// Peek first bytes to detect armor
	header := make([]byte, 35)
	n, _ := io.ReadFull(inFile, header)
	inFile.Seek(0, io.SeekStart)

	var r io.Reader = inFile
	if n >= 35 && bytes.HasPrefix(header[:n], []byte("-----BEGIN AGE ENCRYPTED FILE-----")) {
		ar := armor.NewReader(inFile)
		r = ar
	}

	out, err := age.Decrypt(r, identity)
	if err != nil {
		return fmt.Errorf("failed to decrypt: %w", err)
	}

	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer cleanupIncompleteOutput(outFile, outputPath, &err)

	if _, err := io.Copy(outFile, cancelReader{reader: out, token: token}); err != nil {
		return fmt.Errorf("failed to write decrypted data: %w", err)
	}
	return nil
}

func cleanupIncompleteOutput(file *os.File, outputPath string, err *error) {
	closeErr := file.Close()
	if *err == nil && closeErr != nil {
		*err = fmt.Errorf("failed to close output file: %w", closeErr)
	}
	if *err != nil {
		_ = os.Remove(outputPath)
	}
}

// TarFiles creates a tar archive from the given file paths.
// fileNames[i] is the name to use in the archive for filePaths[i].
// Streams with minimal memory usage.
func TarFiles(filePaths []string, fileNames []string, outputPath string, token *CancelToken) (err error) {
	if len(filePaths) != len(fileNames) {
		return fmt.Errorf("file path and name counts differ")
	}
	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer cleanupIncompleteOutput(outFile, outputPath, &err)

	tw := tar.NewWriter(outFile)
	defer tw.Close()

	for i, path := range filePaths {
		if token.IsCancelled() {
			return errCancelled
		}
		info, err := os.Stat(path)
		if err != nil {
			return fmt.Errorf("failed to stat %s: %w", path, err)
		}

		header, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return fmt.Errorf("failed to create tar header: %w", err)
		}
		header.Name = fileNames[i]

		if err := tw.WriteHeader(header); err != nil {
			return fmt.Errorf("failed to write tar header: %w", err)
		}

		f, err := os.Open(path)
		if err != nil {
			return fmt.Errorf("failed to open %s: %w", path, err)
		}
		if _, err := io.Copy(tw, cancelReader{reader: f, token: token}); err != nil {
			f.Close()
			return fmt.Errorf("failed to write tar data: %w", err)
		}
		f.Close()
	}
	return nil
}

// TarGzipFiles creates a tar.gz archive from the given file paths.
// Streams with minimal memory usage (gzip internal buffer ~32KB).
func TarGzipFiles(filePaths []string, fileNames []string, outputPath string, token *CancelToken) (err error) {
	if len(filePaths) != len(fileNames) {
		return fmt.Errorf("file path and name counts differ")
	}
	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer cleanupIncompleteOutput(outFile, outputPath, &err)

	gw := gzip.NewWriter(outFile)
	defer gw.Close()

	tw := tar.NewWriter(gw)
	defer tw.Close()

	for i, path := range filePaths {
		if token.IsCancelled() {
			return errCancelled
		}
		info, err := os.Stat(path)
		if err != nil {
			return fmt.Errorf("failed to stat %s: %w", path, err)
		}

		header, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return fmt.Errorf("failed to create tar header: %w", err)
		}
		header.Name = fileNames[i]

		if err := tw.WriteHeader(header); err != nil {
			return fmt.Errorf("failed to write tar header: %w", err)
		}

		f, err := os.Open(path)
		if err != nil {
			return fmt.Errorf("failed to open %s: %w", path, err)
		}
		if _, err := io.Copy(tw, cancelReader{reader: f, token: token}); err != nil {
			f.Close()
			return fmt.Errorf("failed to write tar data: %w", err)
		}
		f.Close()
	}
	return nil
}

// TarSingleFile creates a tar archive containing a single file.
func TarSingleFile(filePath string, entryName string, outputPath string, token *CancelToken) (err error) {
	outFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer cleanupIncompleteOutput(outFile, outputPath, &err)

	tw := tar.NewWriter(outFile)
	defer tw.Close()

	info, err := os.Stat(filePath)
	if err != nil {
		return fmt.Errorf("failed to stat %s: %w", filePath, err)
	}

	header, err := tar.FileInfoHeader(info, "")
	if err != nil {
		return fmt.Errorf("failed to create tar header: %w", err)
	}
	header.Name = entryName

	if err := tw.WriteHeader(header); err != nil {
		return fmt.Errorf("failed to write tar header: %w", err)
	}

	f, err := os.Open(filePath)
	if err != nil {
		return fmt.Errorf("failed to open %s: %w", filePath, err)
	}
	defer f.Close()

	if _, err := io.Copy(tw, cancelReader{reader: f, token: token}); err != nil {
		return fmt.Errorf("failed to write tar data: %w", err)
	}
	return nil
}

// TarFilesDelim creates a tar archive from newline-delimited file paths and names.
// gomobile cannot export []string, so we use "\n" as delimiter.
func TarFilesDelim(filePathsDelim string, fileNamesDelim string, outputPath string, token *CancelToken) error {
	paths := strings.Split(filePathsDelim, "\n")
	names := strings.Split(fileNamesDelim, "\n")
	return TarFiles(paths, names, outputPath, token)
}

// TarGzipFilesDelim creates a tar.gz archive from newline-delimited file paths and names.
// gomobile cannot export []string, so we use "\n" as delimiter.
func TarGzipFilesDelim(filePathsDelim string, fileNamesDelim string, outputPath string, token *CancelToken) error {
	paths := strings.Split(filePathsDelim, "\n")
	names := strings.Split(fileNamesDelim, "\n")
	return TarGzipFiles(paths, names, outputPath, token)
}
